server:
  port: 9001

nacos:
  discovery:
    server-addr: 122.112.145.36:8848

spring:
  redis:
    database: 0
    host: 101.35.221.49    # Redis服务器地址，修改为你的地址
    port: 6379          # Redis服务器连接端口
    password: '0224'           # Redis服务器连接密码（默认为空）
    timeout: 3000       # Redis服务器链接超时配置

dubbo:
  application:
    name: Lottery-API
    version: 1.0.0
  registry:
    address: nacos://122.112.145.36:8848
  protocol:
    name: dubbo
    port: -1

wx:
  config:
    originalid: gh_d1f182497123
    appid: wxeb4d761de1aa9c3a
    token: xwbughome
    secret: ad13ada3accc9c2a06edc6d839114fde
    #    originalid: gh_0ea532e7a791
    #    appid: wx5ace327c366c0d62
    #    secret: ba076273d04635cf05a43b1e7cbff3a1
    url:
      domain: https://api.weixin.qq.com
      address:
        getToken: /cgi-bin/token
        createMenu: /cgi-bin/menu/create
